#!/bin/sh

#go swede
setxkbmap se

#fonts - TODO - this shit does not work
#xset +fp /usr/share/fonts
#xset +fp /home/oniichan/fonts
xset fp rehash

#stuffy junk
while true ; do
    xsetroot -name "$(acpi -b | awk 'sub(/,/,"") {print $3, $4}')"
    sleep 1m
done &

# MOAR RICE
compton --config ~/.compton.conf -b

#apply dem smexy colors
xrdb -merge ~/.Xresources

#SNAKE OIL EYE IMPROVEMENT
redshift -l 56.148737:13.558502 -t 6500K:4200K &

#we need a god damn cat as a wallpaper. Why? Because FUCK YOU, that's why
feh --bg-fill /home/kitty/images/wallpaper/cat.jpg 

#tpb is not the pirate bay, but a daemon in this case to deal with ultra leet stuff
tpb -d &

#and why the fuck aren't YOU using dwm?
#Oh, and dmenu is nice ^______^

while true; do
    dwm >/dev/null 2>&1
done
    dmenu_run &
#no EOF here fuck you
